"""Creage news_images table

Revision ID: 6dac7a7d7811
Revises: 5e5d5063cd17
Create Date: 2025-03-29 14:59:34.523021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dac7a7d7811'
down_revision: Union[str, None] = '5e5d5063cd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_images_id'), 'news_images', ['id'], unique=False)
    op.drop_constraint('news_image_key', 'news', type_='unique')
    op.drop_column('news', 'image')
    op.drop_index('idx_news_metrics_view_count', table_name='news_metrics')
    op.create_index('idx_news_metrics_view_count', 'news_metrics', ['view_count'], unique=False, postgresql_using='btree', postgresql_ops={'view_count': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_metrics_view_count', table_name='news_metrics', postgresql_using='btree', postgresql_ops={'view_count': 'DESC'})
    op.create_index('idx_news_metrics_view_count', 'news_metrics', [sa.text('view_count DESC')], unique=False)
    op.add_column('news', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.create_unique_constraint('news_image_key', 'news', ['image'])
    op.drop_index(op.f('ix_news_images_id'), table_name='news_images')
    op.drop_table('news_images')
    # ### end Alembic commands ###
